name: Deploy AWS review
on: 
  pull_request:
    branches-ignore:    
      - 'develop'
      - 'main'
  push:
    branches:
      - '!main'
      - '!develop'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build:review

    - name: Deploy
      if: success()
      run: aws s3 sync ./dist/shi-ft-code-redeemer-tool s3://shift-code-tool-review
